version: '3.9'

services:
  postgres:
    container_name: waggy-container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports: 
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - waggy-app

volumes:
  postgres_data:


networks:
  waggy-app: