# Generated by Django 5.2.3 on 2025-07-01 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Бренд продукта',
                'verbose_name_plural': 'Бренды продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег продукта',
                'verbose_name_plural': 'Теги продуктов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Данное поле заполнять не нужно', verbose_name='Короткая ссылка')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/previews/', verbose_name='Превью')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('quantity', models.IntegerField(default=5, verbose_name='Количество')),
                ('sku', models.CharField(max_length=150, unique=True, verbose_name='SKU')),
                ('size', models.CharField(blank=True, choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('GRAY', 'GRAY')], max_length=10, null=True, verbose_name='Цвет')),
                ('category', models.ManyToManyField(related_name='products', to='categories.category', verbose_name='Категория')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productbrand', verbose_name='Бренд')),
                ('tags', models.ManyToManyField(related_name='tags', to='products.producttag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фотки продуктов',
            },
        ),
    ]
